name: Deploy clojars

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: clojure:lein

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: lein deps
    - name: Deploy to clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.clojars_username }}
        CLOJARS_PASSWORD: ${{ secrets.clojars_password }}
      run: |
        lein release :patch
        lein deploy clojars
